max_population_size: 1000
population_size_q: 1

max_lifespan: 50
maturation_age: 5

# GENOME STRUCTURE
n_neutral_loci: 10
mutation_loci: 5
bits_per_locus: 10

# INITIAL DISTRIBUTIONS
genome_distribution: 1 # proportion of 1's in the genome
# ages_distribution ... all are 0

surv_bound_lo: 0
surv_bound_hi: 1

repr_bound_lo: 0
repr_bound_hi: 1

# MUTATION
mutation_ratio: 0.1
mutrate_distribution: 0.95 # proportion of 1's in the mutation loci
mutation_locus_interpreter: exp # exp or binary
mutation_probability: -1 # if -1, then mutation rate is evolvable

# OVERFLOW HANDLING
overflow_handling: treadmill_random # bottleneck, treadmill_real, treadmill_random
bottleneck_size: 500
cyclicity: False # False or {stage}|{amount}

# MISC
cycle_num: 4000
split_generations: False
split_generations_soft: False 
record_immature: True
# compress_output: True

# REPRODUCTIVE MODE
repr_mode: asexual
recombination_rate: 0.01

# RECORDING
rec_every_nth: 10

#
# RELEVANT:
#
# max_population_size
# population_size_q
# surv_bound_lo
# surv_bound_hi
# repr_bound_lo
# repr_bound_hi
# mutation_ratio
# mutrate_distribution
# overflow_handling
# (bottleneck_size)
#