# # ECOLOGY
# max_population_size: 1000
# overshoot_handling: treadmill_random # bottleneck, treadmill_real, treadmill_random
# # bottleneck_size: 500
# discrete_generations: False
# # discrete_generations_soft: False

# # GENOTYPE
# max_lifespan: 50
# maturation_age: 5
# n_neutral_loci: 10
# n_mutation_loci: 5
# bits_per_locus: 10

# # INITIAL DISTRIBUTIONS
# genome_distribution: 1 # proportion of 1's in the genome or a genome
# mutrate_distribution: 1 # proportion of 1's in the mutation loci

# # PHENOTYPE
# surv_bound_lo: 0
# surv_bound_hi: 1
# repr_bound_lo: 0
# repr_bound_hi: 1
# muta_bound_lo: 0.00001 # 1e-5
# muta_bound_hi: 0.01
# interpreter_surv: decimal # decimal or binary
# interpreter_repr: decimal # decimal or binary
# interpreter_neut: decimal # decimal or exp
# interpreter_muta: exp # decimal
# envmap_rate: 20 # change a bit of environmental map every ? stages

# # REPRODUCTION
# repr_mode: asexual # sexual, asexual
# recombination_rate: 0.01

# # MUTATION
# mutation_ratio: 0.1
# mutation_probability: 0.0001 # mutation rate; if -1, then evolvable

# # BETA
# phenomap_plus: [[1, 0, 0.5], [2, 1, 0.5]]
# population_num: 1
