# use switchdn.yml

PHENOMAP_PLUS:
  [
    [0, 4, 0.7],
    [4, 4, 0.3],
    [4, 5, -0.5],

    [0, 14, 0.7],
    [14, 14, 0.3],
    [14, 15, -0.5],

    [0, 44, 0.7],
    [44, 44, 0.3],
    [44, 45, -0.5],
  ]
