# use switchdn.yml

PHENOMAP_PLUS:
  [
    [0, 4, 0.7],
    [4, 4, 0.3],
    [4, 5, -0.3],

    [0, 11, 0.7],
    [11, 11, 0.3],
    [11, 12, -0.3],

    [0, 44, 0.7],
    [44, 44, 0.3],
    [44, 45, -0.3],
  ]
