# ECOLOGY
MAX_POPULATION_SIZE: 300
OVERSHOOT_EVENT: starvation # starvation, cliff, treadmill_random, treadmill_zoomer, treadmill_boomer
CLIFF_SURVIVORSHIP: False
DISCRETE_GENERATIONS: False

# GENOTYPE
MAX_LIFESPAN: 50
MATURATION_AGE: 10
BITS_PER_LOCUS: 8
HEADSUP: -1 # -1 if no preevolution, 0 for maturity guarantee, +x for headsup

# GENOME STRUCTURE
# agespecific, interpreter, bound low, bound high, initial value
GENOME_STRUCT:
  surv: [true, binary, 0, 1, 1]
  repr: [true, binary, 0, 0.5, 1]
  # neut: [false, binary, 0, 1, 1]
  # muta: [false, binary_exp, 0.0001, 0.01, 0]

GENOME_CONST:
  neut: 1
  muta: 0.001

# REPRODUCTION
REPR_MODE: asexual # sexual, asexual, diasexual (diploid asexual)
RECOMBINATION_RATE: False

# MUTATION
MUTATION_RATIO: 0.1

# RUNTIME
CYCLE_NUM: 1000000 # run ? cycles
LOGGING_RATE: 1000 # log every ? stages

# RECORDING
REC_EVERY_NTH: 1 # record every ?-th individual
FLUSH_RATE: 20000 # flush once ? individuals have been saved
JSON_RATE: 20000 # record json every ? stages
REC_RATE: 10 # record gen, phe, dem every ? JSON flushes
PICKLE_RATE: 250000 # pickle population every ? stages

# PHENOMAP
PHENOMAP_PLUS: [] # [[geno index, pheno index, weight], ...]

# ENVMAP
ENVMAP_RATE: 0 # change a bit of environmental map every ? stages

